// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QuickTest.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidQuickTestPackageString = "02f087f1-2a2e-412e-a3fb-91ad6edd2995";
        public static Guid guidQuickTestPackage = new Guid(guidQuickTestPackageString);

        public const string guidQuickTestPackageCmdSetString = "78bb50c8-df43-4880-bb05-458fd449d8f5";
        public static Guid guidQuickTestPackageCmdSet = new Guid(guidQuickTestPackageCmdSetString);

        public const string guidImagesString = "20180074-419c-47d3-a919-3c8d6d8f4356";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int UnitTestCommandId = 0x0100;
        public const int IntegrationTestCommandId = 0x0101;
        public const int OriginalClassCommandId = 0x0102;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPic3 = 0x0003;
    }
}